### ISSUE TITLE
123

### ISSUE THREAD

**Issue by chaishuhang** [HVision-NKU/SRFormer#3]
![123](https://user-images.githubusercontent.com/129351481/232662660-753e84fb-940d-4bd8-b4fc-dc36f5ac486f.JPG)
您好，自己训练模型后，测试时模型无法加载，您知道是为什么吗？

**Comment by Z-YuPeng** [comment]
Sorry for the late reply. Because I haven't subscribed to the message reminder before, I did not check this issue in the past.  From the figure you provided, it is hard to find the reason.  Have you fixed it? or give more information? 

p.s.  I have now opened the message reminder and will reply as soon as possible

**Comment by Z-YuPeng** [comment]
We will close the issue since it has been inactive for a long time. Feel free to reopen it when you need.
